#+hugo_base_dir: ../../
#+hugo_section: posts

#+title: "Mount to a remote filesystem with sshfs"
#+author: Kanelis Elias
#+date: 2021-10-23

#+hugo_tags: sshfs mount
#+hugo_categories:

#+hugo_weight: 2001
#+hugo_draft: false
#+hugo_auto_set_lastmod: t
#+hugo_custom_front_matter:

* Mount to remote filesystem over SSH with sshfs
** Installing SSHFS
On debian based distro.

#+BEGIN_SRC bash
  sudo apt-get install sshfs
#+END_SRC

** Mounting the Remote File System
Create a local directory in which to mount the remote file system.

#+BEGIN_SRC bash
  sudo mkdir /mnt/name
#+END_SRC

** Temporarily solution
*** Temporarily with password login

#+BEGIN_SRC bash
  sudo sshfs -o allow_other,reconnect user@ip_address:/ /mnt/name
#+END_SRC

*** Temporarily with ssh key authentication

#+BEGIN_SRC bash
  sudo sshfs -o allow_other,reconnect,IdentityFile=/home/user/.ssh/id_rsa user@ip_address:/ /mnt/name/
#+END_SRC

It is important to note that this process provides only a temporary mount point to your droplet. If the virtual server or local machine is powered off or restarted, you will need to use the same process to mount it again.

*** Unmount
When you no longer need the mount point you can simply unmount it with the command

#+BEGIN_SRC bash
  sudo umount /mnt/name
  sudo rmdir /mnt/name
#+END_SRC

** Permanent solution
We will need to edit the /etc/fstab file on the local machine to automatically mount the file system each time the system is booted.

First we need to edit the /etc/fstab file with a text editor.

#+BEGIN_SRC bash
  sudo nano /etc/fstab
#+END_SRC

Add the following entry to the bottom of the file. (there is extra option for automount to work for systemd)
Links with sources:
https://man.archlinux.org/man/mount.8#FILESYSTEM-INDEPENDENT_MOUNT_OPTIONS
https://superuser.com/questions/669287/automount-sshfs-using-fstab-without-mount-a

#+begin_example
user@ip_address:/  /mnt/name  fuse.sshfs  x-systemd.automount,noauto,_netdev,nouser,idmap=user,transform_symlinks,identityfile=/home/tedi/.ssh/id_rsa_jason,allow_other,uid=REMOTE_USER_ID,gid=REMOTE_GROUP_ID,sync,noatime,reconnect,rw 0 0
#+end_example

Save the changes and reboot.

** Warning
It should be noted that permanently mounting your VPS file system locally is a potential security risk. If your local machine is compromised it allows for a direct route to your remote.
Therefore it is not recommended to setup permanent mounts on production servers.
